Easy.CMS.Web/Modules/Common/Controllers/WidgetTemplateController.cs
/* http://www.zkea.net/ Copyright 2016 ZKEASOFT http://www.zkea.net/licenses */
using System.Linq;
using System.Web.Mvc;
using Easy.Data;
using Easy.Extend;
using Easy.Web.Attribute;
using Easy.Web.Authorize;
using Easy.Web.CMS;
using Easy.Web.CMS.WidgetTemplate;
using Easy.Web.Controller;
using Easy.Web.ValueProvider;

namespace Easy.CMS.Common.Controllers
{
    [AdminTheme, DefaultAuthorize(PermissionKeys.ManagePage)]
    public class WidgetTemplateController : BasicController<WidgetTemplateEntity, long, IWidgetTemplateService>
    {
        private readonly ICookie _cookie;
        public WidgetTemplateController(IWidgetTemplateService widgetTemplateService, ICookie cookie)
            : base(widgetTemplateService)
        {
            _cookie = cookie;
        }

        public ActionResult SelectWidget(QueryContext context)
        {
            var viewModel = new WidgetTemplateViewModel
            {
                PageID = context.PageID,
                LayoutID = context.LayoutID,
                ZoneID = context.ZoneID,
                ReturnUrl = context.ReturnUrl,
                CanPasteWidget = context.ZoneID.IsNotNullAndWhiteSpace() && _cookie.GetValue<string>(Const.CopyWidgetCookie).IsNotNullAndWhiteSpace(),
                WidgetTemplates = Service.Get(new DataFilter().OrderBy("[Order]", OrderType.Ascending)).ToList()
            };
            return View(viewModel);
        }
        [HttpPost]
        public ActionResult RedirectToWidget(QueryContext context)
        {
            return RedirectToAction("Create", "Widget", new { module = "admin", context.PageID, context.LayoutID, context.ZoneID, context.WidgetTemplateID, context.ReturnUrl });
        }
    }
}

Easy.CMS.Web/Modules/Common/Views/WidgetTemplate/SelectWidget.cshtml
@using Easy.Web.CMS.WidgetTemplate
@model Easy.Web.CMS.WidgetTemplate.WidgetTemplateViewModel
@{
    Style.Reqiured("Layout").AtFoot();
}
<div class="panel panel-default">
    <div class="panel-heading">
        <div>选择组件</div>
    </div>
    <div class="panel-body template-list">
        @using (Html.BeginForm("RedirectToWidget", "WidgetTemplate", new { module = "admin", Model.PageID, Model.LayoutID, Model.ZoneID, Model.ReturnUrl }))
        {
            foreach (var item in Model.WidgetTemplates.GroupBy(m => m.GroupName).OrderBy(m => m.Key))
            {
                foreach (WidgetTemplateEntity template in item.OrderBy(m => m.Order))
                {
                    <div class="col-lg-2 col-md-3 col-sm-4">
                        <div>
                            <input id="template-@template.ID" type="radio" name="WidgetTemplateID" value="@template.ID" />
                            <label for="template-@template.ID" class="thumbnail">
                                <img src="@Url.Content(template.Thumbnail)" />
                                <span>
                                    @template.Title
                                </span>
                            </label>
                        </div>
                    </div>
                }
            }
            <div class="toolBar">
                <input id="design" type="submit" class="btn btn-primary" value="下一步" />
                @if (Model.CanPasteWidget)
                {
                    <a class="btn btn-warning" href="@Url.Action("PasteAndRedirect", "Widget", new { Model.LayoutID, Model.PageID,Model.ZoneID,Model.ReturnUrl})">
                        <i class="glyphicon glyphicon-paste"></i>
                        粘贴
                    </a>
                }
                <input type="button" class="btn btn-default cancel" value="取消" />
            </div>
        }
    </div>
</div>
@using (Script.AtFoot())
{
    <script type="text/javascript">
        $("input[type=radio]:first").attr("checked", "checked");
    </script>
}