Easy.CMS.Web/Modules/Message/Models/MessageBoxWidget.cs
using Easy.MetaData;
using Easy.Web.CMS.MetaData;
using Easy.Web.CMS.Widget;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Easy.CMS.Message.Models
{
    [DataConfigure(typeof(MessageBoxWidgetMetaData)), Serializable]
    public class MessageBoxWidget : WidgetBase
    {
    }
    class MessageBoxWidgetMetaData : WidgetMetaData<MessageBoxWidget>
    {

    }
}

Easy.CMS.Web/Modules/Message/Models/MessageEntity.cs
using Easy.MetaData;
using Easy.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Easy.CMS.Message.Models
{
    [DataConfigure(typeof(MessageMetaData))]
    public class MessageEntity : EditorEntity
    {
        public int ID { get; set; }
        public string Email { get; set; }
        public string PostMessage { get; set; }
        public string Reply { get; set; }
    }
    class MessageMetaData : DataViewMetaData<MessageEntity>
    {
        protected override void DataConfigure()
        {
            DataTable("CMS_Message");
            DataConfig(m => m.ID).AsIncreasePrimaryKey();
        }

        protected override void ViewConfigure()
        {
            ViewConfig(m => m.ID).AsHidden();
            ViewConfig(m => m.Title).AsTextBox().Required().MaxLength(50).Order(1);
            ViewConfig(m => m.Email).AsTextBox().Email().Required().MaxLength(50).Order(2);
            ViewConfig(m => m.PostMessage).AsTextArea().Required().MaxLength(500).Order(3);
            ViewConfig(m => m.Reply).AsTextArea().MaxLength(500).Order(4);
        }
    }
}

Easy.CMS.Web/Modules/Message/Models/MessageWidget.cs
using Easy.MetaData;
using Easy.Web.CMS.MetaData;
using Easy.Web.CMS.Widget;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Easy.CMS.Message.Models
{
    [DataConfigure(typeof(MessageWidgetMetaData)), Serializable]
    public class MessageWidget : WidgetBase
    {
    }
    class MessageWidgetMetaData : WidgetMetaData<MessageWidget>
    {

    }
}

Easy.CMS.Web/Modules/Message/Controllers/MessageController.cs
using Easy.CMS.Message.Models;
using Easy.CMS.Message.Service;
using Easy.Web.Attribute;
using Easy.Web.Controller;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Easy.CMS.Message.Controllers
{
    [AdminTheme]
    public class MessageController : BasicController<MessageEntity, int, IMessageService>
    {
        public MessageController(IMessageService service) : base(service)
        {
        }
    }
}

Easy.CMS.Web/Modules/Message/Controllers/MessageHandleController.cs
using Easy.CMS.Message.Models;
using Easy.CMS.Message.Service;
using Easy.Web.ValueProvider;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Easy.CMS.Message.Controllers
{
    public class MessageHandleController : Controller
    {
        private readonly IMessageService _messageService;
        private readonly ICookie _cookie;
        public MessageHandleController(IMessageService messageService, ICookie cookie)
        {
            _messageService = messageService;
            _cookie = cookie;
        }

        public ActionResult PostMessage(MessageEntity entity, string redirect)
        {
            if (ModelState.IsValid)
            {
                _cookie.SetValue("Message", "true", 1);
                entity.Status = (int)Constant.RecordStatus.InActive;
                _messageService.Add(entity);
            }
            return Redirect(redirect);
        }

    }
}

Easy.CMS.Web/Modules/Message/Views/Message/Create.cshtml
@model Easy.CMS.Message.Models.MessageEntity
@{
    Script.Reqiured("validate").AtFoot();
}

<div class="panel panel-default">
    <div class="panel-heading">
        新建
    </div>
    <div class="panel-body">
        @using (Html.BeginForm())
        {
            @Html.EditorForModel()
            <div class="toolBar">
                <input type="submit" class="btn btn-primary " value="保存" data-value="@ActionType.Create" />
                <input type="button" class="btn btn-default cancel" value="取消" />
            </div>
        }
    </div>
</div>

Easy.CMS.Web/Modules/Message/Views/Message/Edit.cshtml
@model Easy.CMS.Message.Models.MessageEntity
@{
    Script.Reqiured("validate").AtFoot();
}

<div class="panel panel-default">
    <div class="panel-heading">
        编辑
    </div>
    <div class="panel-body">
        @using (Html.BeginForm())
        {
            @Html.EditorForModel()
            <div class="toolBar">
                <input type="submit" class="btn btn-primary" value="保存" data-value="@ActionType.Update" />
                <input type="button" class="btn btn-default cancel" value="取消" />
            </div>
        }
    </div>
</div>

Easy.CMS.Web/Modules/Message/Views/Message/Index.cshtml
@using Easy.Data
@using Easy.CMS.Message.Models
@{

}
@if (Authorizer.Authorize(Easy.CMS.Message.PermissionKeys.ManageMessage))
{
    <div id="toolBar">
        <a href="@Url.Action("Create")" class="btn btn-primary btn-xs">新建</a>
    </div>
}
@(
 Html.Grid<MessageEntity>().SetColumnTemplate(col => {
     col.Add(m => m.Title, "<a href='"+Url.Action("Edit")+"/{ID}'>{Title}</a>");
 }).SetAsToolBar("#toolBar").ShowCheckbox(m=>m.ID).OrderBy(m=>m.CreateDate, OrderType.Descending)
)

Easy.CMS.Web/Modules/Message/Views/Widget.Message.cshtml
@model Easy.CMS.Message.Models.MessageEntity
@{
    Script.Reqiured("validate").AtFoot();
}
<div class="message">
    @if (Request.Cookies.AllKeys.Any(key => key == "Message"))
    {
        <div class="alert alert-info">
            <h4>Thank You!</h4>
            <p>
                我们已经收到您的留言，我们会在第一时间处理您的信息，并在需要的时候通过邮件与您取得联系。
            </p>
        </div>
    }
    @using (Html.BeginForm("PostMessage", "MessageHandle", FormMethod.Post))
    {
        @Html.HiddenFor(m => m.Status)
        @Html.HiddenFor(m => m.Description)
        @Html.HiddenFor(m => m.Reply)
        <input type="hidden" value="@Request.Url.ToString()" name="redirect" />
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(m => m.Title)
                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control", placeholder = "输入您的名字" })
                    @Html.ValidationMessageFor(m => m.Title)
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(m => m.Email)
                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "输入您的邮箱地址" })
                    @Html.ValidationMessageFor(m => m.Email)
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    @Html.LabelFor(m => m.PostMessage)
                    @Html.TextAreaFor(m => m.PostMessage, new { @class = "form-control", rows = "10", placeholder = "请留言..." })
                    @Html.ValidationMessageFor(m => m.PostMessage)
                </div>
            </div>
        </div>
        <input type="submit" value="提交留言" class="btn btn-primary" />
    }
</div>

Easy.CMS.Web/Modules/Message/Views/Widget.MessageBox.cshtml
@using Easy.CMS.Message.Models
@model IEnumerable<MessageEntity>
<div class="message-box">
    @if (Model == null || !Model.Any())
    {
        <em>还没有留言……</em>
    }
    else
    {
        <div class="container-fluid">
            @{
                var last = Model.Last();
                foreach (var item in Model)
                {
                    <div class="row">
                        <div class="col-xs-2 col-sm-2 col-md-1 bg-primary text-center">
                            <h4 style="word-break:break-all">@item.CreateDate.Value.Year</h4>
                            <p>@item.CreateDate.Value.ToString("M / d")</p>
                        </div>
                        <div class="col-xs-10 col-sm-10 col-md-11">
                            <p>
                              <strong>@item.PostMessage</strong>  
                            </p>
                            <div class="text-muted">
                                @item.Reply
                            </div>
                        </div>
                    </div>
                    if (!item.Equals(last))
                    {
                        <div class="row">
                            <hr />
                        </div>
                    }
                }
            }
        </div>
                }

</div>