Easy.CMS.Web/Modules/Common/Controllers/WidgetController.cs
/* http://www.zkea.net/ Copyright 2016 ZKEASOFT http://www.zkea.net/licenses */
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Easy.Constant;
using Easy.Data;
using Easy.Extend;
using Easy.Web;
using Easy.Web.Attribute;
using Easy.Web.Authorize;
using Easy.Web.CMS;
using Easy.Web.CMS.Widget;
using Easy.Web.CMS.WidgetTemplate;
using Easy.Web.ValueProvider;
using Newtonsoft.Json;
using System.IO;
using Easy.Web.CMS.PackageManger;
using Microsoft.Practices.ServiceLocation;
using Easy.Modules.DataDictionary;

namespace Easy.CMS.Common.Controllers
{
    [AdminTheme, DefaultAuthorize(PermissionKeys.ManagePage)]
    public class WidgetController : Controller
    {
        private readonly IWidgetService _widgetService;
        private readonly IWidgetTemplateService _widgetTemplateService;
        private readonly ICookie _cookie;
        private readonly IPackageInstallerProvider _packageInstallerProvider;

        public WidgetController(IWidgetService widgetService, IWidgetTemplateService widgetTemplateService,
            ICookie cookie, IPackageInstallerProvider packageInstallerProvider)
        {
            _widgetService = widgetService;
            _widgetTemplateService = widgetTemplateService;
            _cookie = cookie;
            _packageInstallerProvider = packageInstallerProvider;
        }

        [ViewDataZones]
        public ActionResult Create(QueryContext context)
        {
            var template = _widgetTemplateService.Get(context.WidgetTemplateID);
            var widget = template.CreateWidgetInstance();
            widget.PageID = context.PageID;
            widget.LayoutID = context.LayoutID;
            widget.ZoneID = context.ZoneID;
            widget.FormView = template.FormView;
            if (widget.PageID.IsNotNullAndWhiteSpace())
            {
                widget.Position = _widgetService.GetAllByPageId(context.PageID).Count(m => m.ZoneID == context.ZoneID) + 1;
            }
            else
            {
                widget.Position = _widgetService.GetByLayoutId(context.LayoutID).Count(m => m.ZoneID == context.ZoneID) + 1;
            }
            ViewBag.WidgetTemplateName = template.Title;
            ViewBag.ReturnUrl = context.ReturnUrl;
            if (template.FormView.IsNotNullAndWhiteSpace())
            {
                return View(template.FormView, widget);
            }
            return View(widget);
        }
        [HttpPost, ViewDataZones]
        [ValidateInput(false)]
        public ActionResult Create(WidgetBase widget, string ReturnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(widget);
            }
            widget.CreateServiceInstance().AddWidget(widget);
            if (widget.ActionType == ActionType.Continue)
            {
                return RedirectToAction("Edit", new { widget.ID, ReturnUrl });
            }
            if (!ReturnUrl.IsNullOrEmpty())
            {
                return Redirect(ReturnUrl);
            }
            if (!widget.PageID.IsNullOrEmpty())
            {
                return RedirectToAction("Design", "Page", new { module = "admin", ID = widget.PageID });
            }
            return RedirectToAction("LayoutWidget", "Layout", new { module = "admin" });
        }
        [ViewDataZones]
        public ActionResult Edit(string ID, string ReturnUrl)
        {
            var widgetBase = _widgetService.Get(ID);
            var widget = widgetBase.CreateServiceInstance().GetWidget(widgetBase);
            ViewBag.ReturnUrl = ReturnUrl;

            var template = _widgetTemplateService.Get(
                m =>
                    m.PartialView == widget.PartialView && m.AssemblyName == widget.AssemblyName &&
                    m.ServiceTypeName == widget.ServiceTypeName && m.ViewModelTypeName == widget.ViewModelTypeName).FirstOrDefault();
            if (template != null)
            {
                ViewBag.WidgetTemplateName = template.Title;
            }
            if (widget.FormView.IsNotNullAndWhiteSpace())
            {
                return View(widget.FormView, widget);
            }
            return View(widget);
        }

        [HttpPost, ViewDataZones]
        [ValidateInput(false)]
        public ActionResult Edit(WidgetBase widget, string ReturnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(widget);
            }
            widget.CreateServiceInstance().UpdateWidget(widget);
            if (!ReturnUrl.IsNullOrEmpty())
            {
                return Redirect(ReturnUrl);
            }
            if (!widget.PageID.IsNullOrEmpty())
            {
                return RedirectToAction("Design", "Page", new { module = "admin", ID = widget.PageID });
            }
            return RedirectToAction("LayoutWidget", "Layout", new { module = "admin" });
        }

        [HttpPost]
        public JsonResult SaveWidgetZone(List<WidgetBase> widgets)
        {
            foreach (var widget in widgets)
            {
                _widgetService.Update(widget, new DataFilter(new List<string> { "ZoneID", "Position" }).Where("ID", OperatorType.Equal, widget.ID));
            }
            return Json(true);
        }
        [HttpPost]
        public JsonResult DeleteWidget(string ID)
        {
            WidgetBase widget = _widgetService.Get(ID);
            if (widget != null)
            {
                widget.CreateServiceInstance().DeleteWidget(ID);
                return Json(ID);
            }
            return Json(false);
        }

        public PartialViewResult Templates()
        {
            return PartialView(_widgetService.Get(m => m.IsTemplate == true));
        }

        [HttpPost]
        public PartialViewResult AppendWidget(WidgetBase widget)
        {
            var widgetPart = _widgetService.ApplyTemplate(widget, ControllerContext);
            if (widgetPart == null)
            {
                widgetPart = new HtmlWidget { PartialView = "Widget.HTML", HTML = "<h1 class='text-danger'><hr/>操作失败，找不到数据源，刷新页面后该消息会消失。<hr/></h1>" }.ToWidgetPart();
            }
            return PartialView("AppendWidget", new DesignWidgetViewModel(widgetPart, widget.PageID));
        }
        [HttpPost]
        public JsonResult CancelTemplate(string Id)
        {
            var widget = _widgetService.Get(Id);
            if (!widget.IsSystem)
            {
                widget.IsTemplate = false;
                if (widget.PageID.IsNotNullAndWhiteSpace() || widget.LayoutID.IsNotNullAndWhiteSpace())
                {
                    _widgetService.Update(widget);
                }
                else
                {
                    widget.CreateServiceInstance().DeleteWidget(Id);
                }
            }
            return Json(Id);
        }
        [HttpPost]
        public JsonResult ToggleClass(string ID, string clas)
        {
            var widget = _widgetService.Get(ID);
            if (widget != null)
            {
                if (widget.StyleClass.IsNotNullAndWhiteSpace() && widget.StyleClass.IndexOf(clas) >= 0)
                {
                    widget.StyleClass = widget.StyleClass.Replace(clas, "").Trim();
                }
                else
                {
                    widget.StyleClass = clas + " " + (widget.StyleClass ?? "");
                    widget.StyleClass = widget.StyleClass.Trim();
                }
                _widgetService.Update(widget);
            }
            return Json(ID);
        }
        [HttpPost]
        public JsonResult SaveCustomStyle(string ID, string style)
        {
            var widget = _widgetService.Get(ID);
            if (widget != null)
            {
                if (style.IsNotNullAndWhiteSpace())
                {
                    widget.StyleClass = widget.CustomClass.Trim() + " style=\"{0}\"".FormatWith(style);
                    widget.StyleClass = widget.StyleClass.Trim();
                }
                else
                {
                    widget.StyleClass = widget.CustomClass;
                }
                _widgetService.Update(widget);
            }
            return Json(ID);
        }
        public FileResult Pack(string ID)
        {
            var widget = _widgetService.Get(ID);
            var widgetPackage = widget.CreateServiceInstance().PackWidget(widget) as WidgetPackage;
            return File(widgetPackage.ToFilePackage(), "Application/zip", widgetPackage.Widget.WidgetName + ".widget");
        }
        public FileResult PackDictionary(int ID, string[] filePath)
        {

            var dataDictionary = ServiceLocator.Current.GetInstance<IDataDictionaryService>().Get(ID);
            var installer = new DataDictionaryPackageInstaller();
            if (filePath != null && filePath.Any())
            {
                installer.OnPacking = () =>
                {
                    List<System.IO.FileInfo> files = new List<System.IO.FileInfo>();
                    foreach (var item in filePath)
                    {
                        files.Add(new System.IO.FileInfo(Server.MapPath(item)));
                    }
                    return files;
                };
            }

            return File(installer.Pack(dataDictionary).ToFilePackage(), "Application/zip", dataDictionary.Title + ".widget");
        }
        [HttpPost]
        public ActionResult InstallWidgetTemplate(string returnUrl)
        {
            if (Request.Files.Count > 0)
            {
                try
                {
                    Package package;
                    var installer = _packageInstallerProvider.CreateInstaller(Request.Files[0].InputStream, out package);
                    if (installer is WidgetPackageInstaller)
                    {
                        var widgetPackage = JsonConvert.DeserializeObject<WidgetPackage>(package.Content.ToString());

Easy.CMS.Web/Modules/Common/Views/Page/Create.cshtml
@model Easy.Web.CMS.Page.PageEntity
@{
    Script.Reqiured("validate").AtFoot();
}

<div class="panel panel-default">
    <div class="panel-heading">
        <div>页面</div>
    </div>
    <div class="panel-body">
        @using (Html.BeginForm())
        {
            @Html.EditorForModel()
            <div class="toolBar">
                <input type="submit" class="btn btn-primary" value="保存"/>
                <input type="button" class="btn btn-default cancel" value="取消"/>
            </div>
        }
    </div>
</div>
@using (Script.AtFoot())
{
    <script type="text/javascript">
        $(function () {
            var url = $("#Url");
            url.data("url", url.val());
        });
        $("#PageUrl").blur(function () {
            var url = $("#Url");
            var parentUrl = url.data("url");
            if (!parentUrl) {
                parentUrl = "~/";
            }
            var thisUrl = $(this).val();
            var replaceValue = ["/", " ", "?", "`", "~", "!", "@@", "#", "$", "%", "^", "&", "*", "(", ")", "-", "+", "[", "]", "{", "}", "\\", "|", ";", ":", "'", "\"", ",", ".", "<", ">"];
            for (var i = 0; i < replaceValue.length; i++) {
                thisUrl = thisUrl.replaceAll(replaceValue[i], "_");
            }
            url.val(parentUrl + thisUrl);
        });
    </script>
}

Easy.CMS.Web/Modules/Common/Views/Page/Design.cshtml
@using Easy.Web.CMS.Widget
@using Easy.Web.CMS.Zone
@model Easy.Web.CMS.Layout.LayoutEntity
@{
    Style.Reqiured("Layout").AtHead();
    Style.Reqiured("Easy").AtHead();
    Script.Reqiured("jQueryUi").AtFoot();
    Script.Reqiured("PageDesign").AtFoot();
    if (Model == null)
    {
        return;
    }
    //Stack<string> colors = new Stack<string>(new[] { "blue", "lightBlue", "red", "green", "orange" });
}

<input type="hidden" id="save-widget-zone-url" value="@Url.Action("SaveWidgetZone", "Widget", new {module = "admin"})" />
<input type="hidden" id="append-widget-url" value="@Url.Action("AppendWidget", "Widget", new { module = "admin" })" />
<input type="hidden" id="pageId" value="@Model.Page.ID" />
@for (int i = 0; i < Model.Html.Count; i++)
{
    var item = Model.Html[i];
    if (item.Html == ZoneEntity.ZoneTag)
    {
        i++;
        var zoneId = Model.Html[i].Html;
        if (zoneId.IsNotNullAndWhiteSpace())
        {
            if (Model.Zones.Any(m => m.ID == zoneId))
            {
                <input type="hidden" class="zoneId" value="@zoneId" />
                <div class="zoneName">
                    <a title="添加组件到该区域"
                       class="add-widget label label-danger"
                       href="@Url.Action("SelectWidget", "WidgetTemplate", new {module = "admin", pageId = Model.Page.ID, ZoneId = zoneId})">
                        <i class="glyphicon glyphicon-plus"></i>
                        @Model.Zones.First(m => m.ID == zoneId).ZoneName
                    </a>
                    @if (ViewBag.CanPasteWidget == true)
                    {
                        <a class="paste-widget label label-warning" title="粘贴复制的组件到该区域"
                           href="@Url.Action("Paste", "Widget", new { module = "admin", PageID = Model.Page.ID, ZoneID = zoneId })">
                            <i class="glyphicon glyphicon-paste"></i>
                            粘贴
                        </a>
                    }
                </div>
            }
            if (Model.ZoneWidgets.ContainsKey(zoneId))
            {
                foreach (WidgetPart widgetPart in Model.ZoneWidgets[zoneId].OrderBy(m => m.Widget.Position).ThenBy(m => m.Widget.WidgetName))
                {
                    @Html.DesignWidget(new DesignWidgetViewModel(widgetPart, Model.Page.ID));
                }
            }
        }
        i++;
    }
    else
    {
        @Html.Raw(item.Html)
    }
}

@Html.Action("Templates", "Widget", new { module = "admin" })

Easy.CMS.Web/Modules/Common/Views/Page/Index.cshtml
@using Easy.CMS.Common
@using Easy.ViewPort.jsTree
@using Easy.Web.CMS.Page
@{
    string pageId = Request.QueryString["PageID"];
    Script.Reqiured("jQueryUi").AtFoot();
    Script.Reqiured("jsTree").AtFoot();
    var pageTree = Html.Tree<PageEntity>().Source("GetPageTree", "Page", new {module = "admin"})
        .AddPlugin(Plugins.ContextMenu)
        .On(Events.Loaded, "loadedPage")
        .CheckCallBack("checkCallBack")
        .On(Events.MoveNode, "moveNode")
        .On(Events.ActiveNode, "ActiveNode");

    if (Authorizer.Authorize(PermissionKeys.ManagePage))
    {
        pageTree.AddPlugin(Plugins.DragAndDrop).AddContextMenuItem(new ContextmenuItem { Label = "新建", Action = "Create", Icon = "glyphicon glyphicon-plus" })
            .AddContextMenuItem(new ContextmenuItem {Label = "编辑", Action = "Edit", Icon = "glyphicon glyphicon-edit", SeparatorAfter = true})
            .AddContextMenuItem(new ContextmenuItem {Label = "预览", Action = "PreView", Icon = "glyphicon glyphicon-search"})
            .AddContextMenuItem(new ContextmenuItem {Label = "查看", Action = "View", Icon = "glyphicon glyphicon-new-window"})
            .AddContextMenuItem(new ContextmenuItem {Label = "发布", Action = "Publish", Icon = "glyphicon glyphicon-open"})
            .AddContextMenuItem(new ContextmenuItem {Label = "设计", Action = "Design", Icon = "glyphicon glyphicon-wrench"});
    }
    else
    {
        pageTree.AddContextMenuItem(new ContextmenuItem {Label = "预览", Action = "PreView", Icon = "glyphicon glyphicon-search"})
            .AddContextMenuItem(new ContextmenuItem {Label = "查看", Action = "View", Icon = "glyphicon glyphicon-new-window"});
    }
}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    页面
                </div>
                <div id="tree-body" class="panel-body" style="overflow:auto;">
                    @pageTree
                </div>
                @if (Authorizer.Authorize(PermissionKeys.ManagePage))
                {
                    <div class="panel-footer">
                        <a href="@Url.Action("Create", new {ParentID = "#"})" class="btn btn-link btn-xs">
                            <i class="glyphicon glyphicon-plus"></i>
                            添加页面
                        </a>
                        <i class="glyphicon glyphicon-question-sign" style="cursor:help" data-toggle="modal" data-target="#help"></i>
                    </div>
                }
            </div>
        </div>
        <div class="col-md-8" id="pageZones"></div>
    </div>
</div>
<div id="help" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">说明</h4>
            </div>
            <div class="modal-body">
                <ul>
                    <li>
                        添加页面：添加顶级页面，即域名下的一级子页面。~/xxxxx
                    </li>
                    <li>
                        <span>右键菜单</span>
                        <ul>
                            <li>
                                添加：添加子页面
                            </li>
                            <li>
                                编辑：编辑选中页面的属性，像标题，SEO关键字等
                            </li>
                            <li>
                                预览：查看最新修改版本
                            </li>
                            <li>
                                查看：查看已发布版本
                            </li>
                            <li>
                                发布：将页面发布到前端可查看
                            </li>
                            <li>
                                设计：进入页面的设计模式
                            </li>
                            <li>
                                布局：修改页面布局。<code>会影响所有使用该布局的页面</code>
                            </li>
                        </ul>
                    </li>
                </ul>
                <hr />
                <p>
                    <strong>注：</strong>
                    页面必须要发布才可以通过网址访问。对页面进行修改不会影响到已发布版本，直到下一次发布。
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
@using (Script.AtFoot())
{
    <script type="text/javascript">
        function Create(node) {
            var parent = node.reference.attr("id");
            window.location.href = '@Url.Action("Create", "Page", new { module = "admin" })' + '?ParentID=' + parent;
        }
        function Edit(node) {
            var id = node.reference.attr("id");
            window.location.href = '@Url.Action("Edit", "Page", new { module = "admin" })' + '/' + id;
        }
        function PreView(node) {
            var id = node.reference.attr("id");
            window.location.href = '@Url.Action("RedirectView", "Page", new { module = "admin" })' + '/' + id;
        }
        function View(node) {
            var id = node.reference.attr("id");
            window.open('@Url.Action("RedirectView", "Page", new { module = "admin" })' + '/' + id + "?preview=false");
        }
        function Design(node) {
            var id = node.reference.attr("id");
            window.location.href = '@Url.Action("Design", "Page", new { module = "admin" })' + '/' + id;
        }
        function Publish(node) {
            var id = node.reference.attr("id");
            Easy.ShowMessageBox("提示", "确定要发布吗？", function () {
                Easy.Block();
                $.post('@Url.Action("Publish")', { id: id }, function () {
                    $(".jstree").jstree().refresh();
                    Easy.UnBlock();
                });
            }, true);
        }
        function ActiveNode(node, selected) {
            location.hash = selected.node.id;
            var pageZones = $("#pageZones");
            pageZones.empty();
            $.post("@Url.Action("PageZones", "Page", new { module = "admin" })", { PageID: selected.node.id }, function (html) {
                pageZones.html(html);
            }, "html");
        }
        function checkCallBack(operation, node, node_parent, node_position, more) {
            return operation == "move_node" && node.parent == node_parent.id;
        }
        function moveNode(node, parent) {
            $.post("@Url.Action("MovePage")", { id: parent.node.id, position: parent.position + 1, oldPosition: parent.old_position + 1 }, function () {

            }, "json");
        }
        function loadedPage(p) {
            if (location.hash && location.hash != "#") {
                $(p.target).find("a" + location.hash).trigger("click");
            } else {
                $(".jstree-node:first a.jstree-anchor:first", p.target).trigger("click");
            }
        }
        $(document).on("click", ".fullRowList .delete", function () {
            var id = $(this).data("widgetid");
            Easy.ShowMessageBox("提示", "确定要删除该组件吗？", function () {
                $.post("@Url.Action("DeleteWidget", "Widget", new { module = "admin" })", { ID: id }, function (data) {
                    if (data) {
                        $("#widget_" + id).remove();
                    }
                }, "json");
            }, true, 10);
        }).on("click", ".publish-page",function() {
            var btn = $(this);
            Publish({
                reference: {
                    attr: function (id) {
                return btn.data(id);
            }}});
        });
        if (!location.hash) {
            location.hash = '@(pageId)';
        }
        $(function () {
            $("#tree-body").css("max-height",$(window).height() - 240);
        });
    </script>
}

Easy.CMS.Web/Modules/Common/Views/Page/PageZones.cshtml
@using Easy.CMS.Common
@using Easy.Web.CMS.Zone
@model Easy.CMS.Common.ViewModels.LayoutZonesViewModel
@{
    Layout = null;
    string returnUrl = Url.Action("Index", "Page", new { module = "admin", Model.PageID });
    var noZoneWidgets = Model.Widgets.Where(m => Model.Zones.All(n => n.ID != m.ZoneID));
}

@if (noZoneWidgets.Any())
{
    <div class="panel panel-danger">
        <div class="panel-heading">
            <span class="badge">须要处理</span>
        </div>
        <div class="panel-body">
            <ul id="noZoneWidgets" class="fullRowList">
                @foreach (var widget in noZoneWidgets.OrderBy(m => m.Position))
                {
                    <li id="widget_@widget.ID" class="widget" data-widgetid="@widget.ID">
                        @if (widget.LayoutID.IsNotNullAndWhiteSpace())
                        {
                            <span class="badge">布局</span>
                        }
                        @if (Authorizer.Authorize(PermissionKeys.ManagePage))
                        {
                            <a href="@Url.Action("Edit", "Widget", new {module = "admin", widget.ID, ReturnUrl = returnUrl})"><i class="glyphicon glyphicon-edit"></i></a>
                            <a href="javascript:void(0)" class="delete" data-widgetid="@widget.ID"><i class="glyphicon glyphicon-trash"></i></a>
                        }
                        @widget.WidgetName
                    </li>
                }
            </ul>

        </div>
        <div class="panel-footer">
            <span class="description">
                组件不能正确地显示在页面中，可能是因为您切换了布局或删除了原先的区域
            </span>
        </div>
    </div>
}

<div class="panel  panel-default">
    <div class="panel-heading">
        @Model.Page.Title
    </div>
    <div class="simplePreview">
        <div class="simpleDesign">
            @for (int i = 0; i < Model.LayoutHtml.Count; i++)
            {
                var itemHtml = Model.LayoutHtml[i];
                if (itemHtml.Html == ZoneEntity.ZoneTag)
                {
                    i++;
                    itemHtml = Model.LayoutHtml[i];
                    var zone = Model.Zones.Where(m => m.ID == itemHtml.Html);

                    foreach (var item in zone)
                    {
                        <div class="panel panel-success panel-relative">
                            <div class="panel-toolbar">
                                @if (Authorizer.Authorize(PermissionKeys.ManagePage))
                                {
                                    <a class="label label-danger" title="添加组件到该区域" href="@Url.Action("SelectWidget", "WidgetTemplate", new {module = "admin", Model.PageID, ZoneID = item.ID, ReturnUrl = returnUrl})">
                                        <i class="glyphicon glyphicon-plus"></i>
                                        @item.ZoneName
                                    </a>
                                }
                                else
                                {
                                    <a class="label label-danger" title="区域名称" href="#">
                                        <i class="glyphicon glyphicon-plus"></i>
                                        @item.ZoneName
                                    </a>
                                }
                            </div>
                            <ul data-zoneid="@item.ID" class="fullRowList widgets connectedSortable">
                                @foreach (var widget in Model.Widgets.Where(m => m.ZoneID == item.ID).OrderBy(m => m.Position).ThenBy(m => m.WidgetName))
                                {
                                    <li id="widget_@widget.ID" class="widget" data-widgetid="@widget.ID">
                                        @if (widget.LayoutID.IsNotNullAndWhiteSpace())
                                        {
                                            <span class="label label-info">布局</span>
                                        }
                                        @if (Authorizer.Authorize(PermissionKeys.ManagePage))
                                        {
                                            <a href="@Url.Action("Edit", "Widget", new { module = "admin", widget.ID, ReturnUrl = returnUrl })"><i class="glyphicon glyphicon-edit"></i></a>
                                            <a href="javascript:void(0)" class="delete" data-widgetid="@widget.ID"><i class="glyphicon glyphicon-trash"></i></a>
                                        }
                                        @widget.WidgetName
                                    </li>
                                }
                            </ul>

                        </div>
                    }

                    i++;
                }
                else
                {
                    @Html.Raw(itemHtml.NoStyleHtml)
                }

            }
        </div>
    </div>
    <div class="panel-footer">
        <div class="btn-group">
            @if (Authorizer.Authorize(PermissionKeys.ManagePage))
            {
                <a class="btn btn-primary" href="@Url.Action("Design", new {ID = Model.PageID})">
                    <i class="glyphicon glyphicon-wrench"></i>
                    设计
                </a>
            }
            <a class="btn btn-primary" href="@Url.Action("RedirectView", "Page", new {module = "admin", ID = Model.PageID})">
                <i class="glyphicon glyphicon-search"></i>
                预览
            </a>
            @if (Authorizer.Authorize(PermissionKeys.ManagePage))
            {
                <a class="btn btn-primary" href="@Url.Action("Edit", new {ID = Model.PageID})">
                    <i class="glyphicon glyphicon-edit"></i>
                    属性
                </a>
            }
            @if (Authorizer.Authorize(PermissionKeys.ManageLayout))
            {
                <a class="btn btn-primary" href="@Url.Action("Design", "Layout", new {module = "admin", ID = Model.LayoutID, Model.PageID})">
                    <i class="glyphicon glyphicon-th-list"></i>
                    布局
                </a>
            }
            <a class="btn btn-primary"
               href="@Url.Action("RedirectView", "Page", new {module = "admin", ID = Model.PageID, preview = false})"
               target="_blank">
                <i class="glyphicon glyphicon-new-window"></i>
                查看已发布版本
            </a>
            @if (Authorizer.Authorize(PermissionKeys.ManagePage))
            {
                <a class="btn btn-primary publish-page" data-id="@Model.PageID" href="javascript:void(0)">
                    <i class="glyphicon glyphicon-open"></i>
                    发布
                </a>
            }
        </div>
    </div>
</div>

@if (Authorizer.Authorize(PermissionKeys.ManagePage))
{
    @Html.Partial("SortWidget.Script")
}

Easy.CMS.Web/Modules/Common/Views/Page/PreView.cshtml
@using Easy.Web.CMS.Zone
@model Easy.Web.CMS.Layout.LayoutEntity
@{
    if (Model == null)
    {
        return;
    }
}
@for (int i = 0; i < Model.Html.Count; i++)
{
    var item = Model.Html[i];
    if (item.Html == ZoneEntity.ZoneTag)
    {
        i++;
        var zoneId = Model.Html[i].Html;
        if (zoneId.IsNotNullAndWhiteSpace())
        {
            if (Model.ZoneWidgets.ContainsKey(zoneId))
            {
                foreach (var widgetPart in Model.ZoneWidgets[zoneId].OrderBy(m => m.Widget.Position).ThenBy(m => m.Widget.WidgetName))
                {
                    <div style="@widgetPart.Widget.CustomStyle">
                        <div class="widget @widgetPart.Widget.CustomClass">
                            @if (widgetPart.Widget.Title.IsNotNullAndWhiteSpace())
                            {
                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        @widgetPart.Widget.Title
                                    </div>
                                    <div class="panel-body">
                                        @Html.DisPlayWidget(widgetPart)
                                    </div>
                                </div>
                            }
                            else
                            {
                                @Html.DisPlayWidget(widgetPart)
                            }
                        </div>
                    </div>
                }
            }
        }
        i++;
    }
    else
    {
        @Html.Raw(item.Html)
    }
}

Easy.CMS.Web/Modules/Common/Views/Page/Select.cshtml
@using Easy.ViewPort.jsTree
@using Easy.Web.CMS.Page
@{
    ViewBag.Title = "选择页面";
    Script.Reqiured("jsTree").AtFoot();
}


@(
 Html.Tree<PageEntity>().Source("GetPageTree", "Page", new { module = "admin" }).On(Events.SelectNode, "Select")
)
@using (Script.AtFoot())
{
    <script type="text/javascript">
        function Select(node, selected, e) {
            Set(selected.node.a_attr.Url);
        }
    </script>
}